### ISSUE TITLE
Archivematica source checkout hangs forever if target path already exists

### ISSUE THREAD

**Issue by mistydemeo** [artefactual-labs/ansible-archivematica-src#40]
If the `archivematica_src_dir` variable points to a location outside the vagrant VM, for example, `/vagrant/src`, and that location already exists and already has an Archivematica source checkout, Vagrant will hang forever while performing the checkout. This may only happen if the checkout in `/vagrant/src` has local changes.

**Comment by sevein** [comment]
@mistydemeo can you send us the name of the task where ansible hangs?

**Comment by mistydemeo** [comment]
It's the "Checkout Archivematica code" task, IIRC.

**Comment by sevein** [comment]
There is an issue in ansible that may not be directly related but could give you some ideas on how to diagnose it if you have a chance: https://git.io/v2Ugj.

**Comment by sevein** [comment]
Likely due to and old bug in Ansible already solved. This hasn't came up again in a long time. Going to close.
