### ISSUE TITLE
gunicorn config: add option to disable sendfile

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-archivematica-src#61]
Have experienced errors when downloading big SIPs from the Storage Service when sendfile is enabled in gunicorn (default behaviour). Adding the `--no-sendfile` option when running Storage Service's gunicorn fixes it.

**Comment by sevein** [comment]
Far from ideal though since sendfile() is what really makes it performant as the read and write happens within the kernel. Can you share the errors that you experienced? Hopefully we can solve them?

**Comment by hakamine** [comment]
The error is here:
https://projects.artefactual.com/issues/9874#note-5

**Comment by sevein** [comment]
Can you reproduce if you download directly from gunicorn? i.e. bypass nginx proxy

**Comment by sevein** [comment]
New environment variables `AM_GUNICORN_SENDFILE` (in `qa/1.x`) and `SS_GUNICORN_SENDFILE` (in `qa/0.x`) should do this, e.g.:

```
AM_GUNICORN_SENDFILE=false
SS_GUNICORN_SENDFILE=true
```

This is the code that parses the value of the environment string, in case you're wondering how that happens: https://github.com/benoitc/gunicorn/blob/1edf8fcff5cf19e1580a927b10acdedbda2152a0/gunicorn/config.py#L196-L205.

**Comment by sevein** [comment]
See also files [dashboard.gunicorn-config.py](https://github.com/artefactual/archivematica/blob/6aab059be68802d668c4d7232801d43e487bee99/src/dashboard/install/dashboard.gunicorn-config.py#L46) and [storage-service.gunicorn-config.py](https://github.com/artefactual/archivematica-storage-service/blob/1d1f7bb84a6b86e1348c060e8e03b62b54df6d19/install/storage-service.gunicorn-config.py#L50). These are the Gunicorn configuration files that we bundle where `AM_GUNICORN_SENDFILE` and `SS_GUNICORN_SENDFILE` are looked up.
