### ISSUE TITLE
Handle upgrades when /var/archivematica/sharedDirectory is a symlink

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-archivematica-src#62]
Sometimes /var/archivematica/sharedDirectory is a symlink, in order to use a separate mount for increased processing space. Currently the playbook stops with an error

**Comment by hakamine** [comment]
should be fixed by #96

**Comment by Hwesta** [comment]
BTW if the commit contains an issue # Github will auto-link it here, and 'closes <issue #>' it will close this automatically. https://help.github.com/articles/closing-issues-via-commit-messages/
