### ISSUE TITLE
Update ghostscript installation

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-archivematica-src#65]
Ghostscript (gs) is used by archivematica for normalization.
The ghostcript version (9.10) provided in ubuntu 14.04 sometimes produces an output that causes archivematica to break  ( https://projects.artefactual.com/issues/9243  )

**Comment by sevein** [comment]
Is this still a problem? Can we close the issue?

**Comment by hakamine** [comment]
I don't think this has been addressed yet, but I am not sure if we need to fix it here. Currently the workaround is to manually install a newer version of ghostscript on installations that require it (i.e., when the ingested files produce errors with the old version of ghostscript). 
Recent versions of ghostcript are available from ghostcript.com, but .tgz only, not packages. We could try to build newer packages and add to the archivematica externals repository, in this case the ansible role wouldn't need changes. Also ubuntu 16.04 ships with a newer version (9.18).

**Comment by sevein** [comment]
Should we close this issue and consider https://github.com/artefactual/archivematica/issues/725 its replacement?

**Comment by hakamine** [comment]
Yes! 🕵️  Closing it here now
