### ISSUE TITLE
allow mysql password to be reset for archivematica user

### ISSUE THREAD

**Issue by jhsimpson** [artefactual-labs/ansible-archivematica-src#72]
Archivematica connects to mysql using credentials stored in /etc/archivematica/archivematicaCommon/dbsettings .  

This ansible role should have a way to change the username and/or password used, and update the config file used by archivematica.

**Comment by sevein** [comment]
@jhsimpson, I've submitted #135 which adds some instructions to our README about the new way to define environment variables in our `qa/1.7.x` branch of the role. It's improvable but better than nothing and I think it solves your question.

But I'm unclear whether you wanted to change the actual user credentials in the MySQL database. If that's the case, I'd say that's beyond the scope of this role. Perhaps you can get that done via the percona role or just using the CLI.

**Comment by sevein** [comment]
We'll include a full list of environment variables in the docs of AM 1.7. We haven't decided yet the location but that won't be the hardest issue.

**Comment by scollazo** [comment]
The database is now configured using percona role, and custom password can be set as a variable:
https://github.com/artefactual-labs/ansible-archivematica-src/blob/stable/1.8.x/defaults/main.yml#L42
