### ISSUE TITLE
update installed mediainfo versions

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-archivematica-src#86]
Versions of mediainfo provided by ubuntu default repositories are old. Instead, install updated versions from  ppa:djcj/mediainfo (which provide newer versions) or downloading packages from https://mediaarea.net/en/MediaInfo/Download/Ubuntu (which has the latest). In either case be sure to install not only package mediainfo, but also the required dependencies libmediainfo0, libzen0 (missing to do this causes mediainfo errors )

**Comment by scollazo** [comment]
Updated mediaconch packages were added to our ubuntu-extras and centos-extras repositories.
