### ISSUE TITLE
Make nginx/gunicorn the default web server for the dashboard and the storage service

### ISSUE THREAD

**Issue by hakamine** [artefactual-labs/ansible-archivematica-src#93]
It should be just enough to change the default values of a couple of variables (archivematica_src_ss_gunicorn and archivematica_src_am_dashboard_gunicorn), but also need to update the README examples.

**Comment by sevein** [comment]
In the `qa/1.7.x` branch, Apache/mod_wsgi was totally removed.
See e228ae4 (part of #123) for more details.
