### ISSUE TITLE
Dashboard, MCPServer and MCPClient are not using virtual environments

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/ansible-archivematica-src#94]

**Comment by minusdavid** [comment]
I wonder if this relates to the problem I'm having when using Vagrant and Ansible:

TASK [artefactual.archivematica-src : Run migrations (within dashboard virtualenv)] ***
fatal: [am-local]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput --settings=settings.common --pythonpath=/usr/lib/archivematica/archivematicaCommon", "failed": true, "msg": "\n:stderr: Traceback (most recent call last):\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line\n    utility.execute()\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 328, in execute\n    django.setup()\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/apps/registry.py\", line 85, in populate\n    app_config = AppConfig.create(entry)\n  File \"/usr/share/python/archivematica-dashboard/local/lib/python2.7/site-packages/django/apps/config.py\", line 86, in create\n    module = import_module(entry)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\nImportError: No module named fpr\n", "path": "/usr/share/python/archivematica-dashboard/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin", "state": "absent", "syspath": ["/tmp/ansible_f2HkgX", "/tmp/ansible_f2HkgX/ansible_modlib.zip", "/tmp/ansible_f2HkgX/ansible_modlib.zip", "/usr/lib/python2.7", "/usr/lib/python2.7/plat-x86_64-linux-gnu", "/usr/lib/python2.7/lib-tk", "/usr/lib/python2.7/lib-old", "/usr/lib/python2.7/lib-dynload", "/usr/local/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages"]}
        to retry, use: --limit @/vagrant/singlenode.retry

**Comment by minusdavid** [comment]
But maybe not. I'll just raise my own issue...

**Comment by sevein** [comment]
This seems to be the important bit in the error you've shared: `ImportError: No module named fpr`. Can you share some details about how you're deploying? Things that could help:

- Are you using deploy-pub? If that's the case, which playbook?
- Which branch of AM are you deploying?

**Comment by minusdavid** [comment]
I'm not that familiar with Archivematica, Django, or virtualenv, but I did trace that error back to /usr/share/archivematica/dashboard/settings/common.py, but I'm a bit stuck there*. 

Yes, I'm using deploy-pub, and invoking Ansible via Vagrant**, so it looks like 'singlenode.yml' is the playbook. 

I think I'm using stable/1.6.x as per vars-singlenode-1.6.yml. 

*I'm comparing against a Ubuntu package install and using "dpkg -L archivematica-dashboard" to see where things should be... I also see /usr/share/archivematica/dashboard/fpr and /usr/share/archivematica/dashboard/external/archivematica-fpr-admin/fpr... and that latter one looks like the module?

**I am using a modified Vagrantfile which allows me to run Ansible on the guest rather than the host since I'm using a Windows host, but I don't think that should be relevant.

**Comment by minusdavid** [comment]
Oh I think I might see it...

**Comment by minusdavid** [comment]
On the Ubuntu package install /usr/share/archivematica/dashboard/fpr is a symlink to /usr/share/archivematica/dashboard/external/archivematica-fpr-admin/fpr.

But on the Ansible install, /usr/share/archivematica/dashboard/fpr is just a file that says "external/archivematica-fpr-admin/fpr" inside it.

**Comment by minusdavid** [comment]
The symlink would fix the path problem...

**Comment by minusdavid** [comment]
Looks like /vagrant/src/archivematica/src/dashboard/src/fpr is what becomes /usr/share/archivematica/dashboard/fpr...

**Comment by minusdavid** [comment]
Sorry, should I stop spamming this thread and just open my own issue now?

**Comment by minusdavid** [comment]
Ahh it's stored in Git as a symlink...

**Comment by minusdavid** [comment]
And because I'm using Windows as a host... it's basically corrupting the file...

**Comment by minusdavid** [comment]
Ahh, I think I could've configured Git for Windows to handle Symlinks... I'll try that.

**Comment by sevein** [comment]
> Sorry, should I stop spamming this thread and just open my own issue now?

Sure, feel free to file a new issue!

In 1.7 we ditched the git submodule and installed archivematica-fpr-admin using pip - meaning no more symlinks. I've been playing today with https://github.com/artefactual/deploy-pub/tree/master/playbooks/archivematica-xenial (using requirements-qa.yml and vars-singlenode-qa.yml) and the installation was successful.

**Comment by minusdavid** [comment]
Nice! That would make things easier for me.

I noticed there is a symlink in deploy-pub/play-books/atom, and I'm going to hunt around for some more  once I've got it sorted.

The following two links set me on the right path. With the latest Git for Windows, if I do the clone as an Administrator, the symlinks get created correctly. Just about to make my Vagrant file changes again (too slow on the 'git commit' and accidentally nuked them), and then try a vagrant up again from a Windows host.
https://stackoverflow.com/questions/5917249/git-symlinks-in-windows
https://stackoverflow.com/questions/11662868/what-happens-when-i-clone-a-repository-with-symlinks-on-windows

**Comment by minusdavid** [comment]
Actually, while I have you here @sevein, is there a way for non-Artefactual people to get access to the wiki?

Or is there a way for me to request wiki modifications?

If you do accept my changes to the Vagrant file, I'd want to add a caveat about the symlinks on the wiki about people trying to install from a Windows host.

**Comment by sevein** [comment]
I think you should be able to request an account here: https://wiki.archivematica.org/Special:RequestAccount.

If you want to contribute to the [website docs](https://www.archivematica.org/docs), this is the repo where you can send your pull requests: https://github.com/artefactual/archivematica-docs.

**Comment by minusdavid** [comment]
Thanks :)

This Windows stuff is wild. I had to use the Administrator account to clone the repo for the symlinks to work, but vagrant up as an Administrator failed miserably. But trying vagrant up again as my regular user and it's working as expected so far...

**Comment by minusdavid** [comment]
So going back to what this issue is really about... Dashboard, MCPServer, and MCPClient aren't using virtual environments? At a glance it looks like they are? But I say that as someone unfamiliar with virtualenv and Python projects overall*.

*I've just done some Python programming for utilities and little things at home.

**Comment by minusdavid** [comment]
@sevein By chance is there an IRC channel or some other type of live place where developers discuss issues? I'm evaluating the Ubuntu package based install at the moment and finding some issues... but they might not be worth logging on Github or Redmine.

**Comment by sevein** [comment]
> By chance is there an IRC channel or some other type of live place where developers discuss issues?

The archivematica-tech mailing list is the best place I can think of: https://groups.google.com/forum/#!forum/archivematica-tech.

**Comment by sevein** [comment]
@scollazo @hakamine - I'm going to close this issue ok? Feel free to open again if you think there's something left that needs to be addressed.
